Repository woowa-techcamp-2022/android-banchan-07, pull requests merged in 2022-08, with the labels that each got.

#3 [CHORE] #1 - project styling
  presentation/src/main/res/font/outfit.xml
  presentation/src/main/res/font/outfit_black.ttf
  presentation/src/main/res/font/outfit_bold.ttf
  presentation/src/main/res/font/outfit_extra_bold.ttf
  presentation/src/main/res/font/outfit_extra_light.ttf
  presentation/src/main/res/font/outfit_light.ttf
  presentation/src/main/res/font/outfit_medium.ttf
  presentation/src/main/res/font/outfit_regular.ttf
  presentation/src/main/res/font/outfit_semibold.ttf
  presentation/src/main/res/font/outfit_thin.ttf
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/themes.xml
Labels: 윤재, 지혜, chore

#5 [CHORE] #4 - project library
  build.gradle
  data/build.gradle
  domain/build.gradle
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt
  presentation/src/main/java/com/woowahan/ordering/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/LocalModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/RemoteModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/RepositoryModule.kt
Labels: 윤재, 지혜, chore

#7 [FEAT] #6 - room db
  data/build.gradle
  data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/datasource/RecentlyDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/entity/CartEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/OrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/RecentlyEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/RecentlyDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/RecentlyDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/local/db/AppDatabase.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/OrderMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt
  data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/RecentlyRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Order.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Result.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/RecentlyRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/DeleteCartUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/InsertCartUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/UpdateCartUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/InsertOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/GetRecentlyUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/GetSimpleRecentlyUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/InsertRecentlyUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/UpdateRecentlyUseCase.kt
  presentation/build.gradle
  presentation/src/androidTest/java/com/woowahan/ordering/CartDaoTest.kt
  presentation/src/main/java/com/woowahan/ordering/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/LocalModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/RecentlyUseCaseModule.kt
Labels: feature, 윤재, 지혜

#9 [REFECTOR] #8 - Variable Name 'Name' To 'Title'
  data/src/main/java/com/woowahan/ordering/data/entity/CartEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/RecentlyEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
Labels: fix, 윤재

#12 [FIX] #10 - 잘못된 쿼리 Field 수정
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
Labels: fix, 윤재

#14 [FEAT] API 연동
  data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/datasource/FoodDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/entity/BestEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/FoodDetailEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/FoodDetailResponse.kt
  data/src/main/java/com/woowahan/ordering/data/entity/FoodEntity.kt
  data/src/main/java/com/woowahan/ordering/data/entity/ListResponse.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/BestMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodDetailMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodMapper.kt
  data/src/main/java/com/woowahan/ordering/data/remote/base/BaseRemote.kt
  data/src/main/java/com/woowahan/ordering/data/remote/datasource/FoodDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/remote/service/FoodService.kt
  data/src/main/java/com/woowahan/ordering/data/repository/FoodRepositoryImpl.kt
  data/src/main/java/com/woowahan/ordering/data/util/MoneyUtil.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Best.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Food.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/FoodDetail.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Menu.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/FoodRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetFoodDetailUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/RemoteModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/FoodUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/util/NetworkUtil.kt
Labels: feature, 윤재, 지혜, done

#16 [FEAT] #15 - MainActivity Container 설정
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/util/FragmentReplace.kt
  presentation/src/main/res/drawable/bg_toolbar_cart_menu_count.xml
  presentation/src/main/res/drawable/bg_toolbar_menu_button_ripple.xml
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_cart_disabled.xml
  presentation/src/main/res/drawable/ic_cart_enabled.xml
  presentation/src/main/res/drawable/ic_reload.xml
  presentation/src/main/res/drawable/ic_user_disabled.xml
  presentation/src/main/res/drawable/ic_user_enabled.xml
  presentation/src/main/res/layout/action_cart.xml
  presentation/src/main/res/layout/action_order.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/menu/menu_toolbar_home.xml
  presentation/src/main/res/menu/menu_toolbar_order.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: feature, 윤재, 지혜

#18 [FEAT] #17 - HomeFragment Container
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/ViewPagerAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/kind/OtherKind.kt
  presentation/src/main/java/com/woowahan/ordering/ui/util/FragmentReplace.kt
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_main_dish.xml
  presentation/src/main/res/layout/fragment_other_dish.xml
  presentation/src/main/res/values/array_tab.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: feature, 윤재, 지혜

#21 [CHORE] 아이콘 드로어블 추가 및 이미지 크기 정의
  presentation/src/main/res/drawable/ic_arrow_right.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_checkbox_checked.xml
  presentation/src/main/res/drawable/ic_checkbox_empty.xml
  presentation/src/main/res/drawable/ic_close.xml
  presentation/src/main/res/drawable/ic_down.xml
  presentation/src/main/res/drawable/ic_grid_normal.xml
  presentation/src/main/res/drawable/ic_grid_selected.xml
  presentation/src/main/res/drawable/ic_linear_normal.xml
  presentation/src/main/res/drawable/ic_linear_selected.xml
  presentation/src/main/res/drawable/ic_minus.xml
  presentation/src/main/res/drawable/ic_plus.xml
  presentation/src/main/res/values/dimen_size.xml
Labels: 지혜, done, chore

#24 [FEAT] #23 - BestFragment
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodGridAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/HeaderAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/util/SizeUtil.kt
  presentation/src/main/res/drawable/bg_best_chip.xml
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/item_food_best.xml
  presentation/src/main/res/layout/item_food_grid.xml
  presentation/src/main/res/layout/item_food_linear.xml
  presentation/src/main/res/layout/item_header.xml
  presentation/src/main/res/values/dimen_size.xml
Labels: feature, 윤재, 지혜

#26 [FEAT] OtherDishFragment
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/SortType.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/HeaderAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
  presentation/src/main/res/drawable/bg_spinner.xml
  presentation/src/main/res/layout/fragment_other_dish.xml
  presentation/src/main/res/layout/item_count_and_filter.xml
  presentation/src/main/res/layout/spinner_filter_dropdown.xml
  presentation/src/main/res/layout/spinner_filter_top.xml
  presentation/src/main/res/values/array_spinner.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, 윤재, 지혜

#28 [FIX] #27 - Spinner Adapter의 변수에 생성된 객체가 존재하지 않을 때만 객체 생성
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FilterAdapter.kt
Labels: fix, 윤재, done

#30 [FEAT] #29 - MainDishFragment
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodGridAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/TypeAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt
  presentation/src/main/res/drawable/bg_linear_grid_selector.xml
  presentation/src/main/res/drawable/ic_grid.xml
  presentation/src/main/res/drawable/ic_linear.xml
  presentation/src/main/res/layout/fragment_main_dish.xml
  presentation/src/main/res/layout/item_food_linear.xml
  presentation/src/main/res/layout/item_type_and_filter.xml
Labels: feature, 윤재, done

#36 [FIX] #35 - HomeFragment
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/util/FragmentReplace.kt
  presentation/src/main/java/com/woowahan/ordering/ui/widget/OrientationAwareRecyclerView.kt
  presentation/src/main/res/layout/fragment_best.xml
Labels: fix, 윤재, done

#40 [FIX] #39 - 어댑터 초기화 시 lateinit 사용
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
Labels: fix, 윤재, done

#43 [FEAT] #37 - DetailFragment
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodDetailMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/FoodDetail.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailImagesFooterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailInfoAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailThumbImagesAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/ImagesViewPagerAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/drawable/bg_indicator_selector.xml
  presentation/src/main/res/layout/fragment_detail.xml
  presentation/src/main/res/layout/item_detail_images.xml
  presentation/src/main/res/layout/item_detail_info.xml
  presentation/src/main/res/layout/item_image_footer.xml
  presentation/src/main/res/layout/item_image_view_pager.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, 윤재, done

#46 [FIX] #44 - Themes
  presentation/src/main/res/layout/item_food_grid.xml
  presentation/src/main/res/layout/item_food_linear.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/themes.xml
Labels: fix, 윤재, in progress

#41 [FEAT] 장바구니 바텀시트 데이터 연결
  data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt
  presentation/src/main/java/com/woowahan/ordering/ui/UiState.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartDialogFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/layout/item_food_grid.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/style_rounded_dialog.xml
Labels: feature, 지혜, done

#51 [FIX] #50 - 스피너 초기화 현상
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
Labels: fix, 윤재, done

#49 [FEAT] #37 - DetailFragment
  data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/entity/CartEntity.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/InsertCartUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailInfoAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/IsExistsCartDialogFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/uistate/DetailUiState.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/item_detail_info.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, refactor, 윤재, done

#52 [FEAT] #15 - MainActivity
  data/build.gradle
  data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainViewModel.kt
  presentation/src/main/res/layout/action_cart.xml
Labels: feature, 윤재, done

#59 [FEAT] #37 - DetailFragment
  data/src/main/java/com/woowahan/ordering/data/local/dao/RecentlyDao.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/item_detail_info.xml
Labels: feature, 윤재, done

#62 [FIX] #61 - CartFragment
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/res/layout/item_cart_recently.xml
Labels: fix, 윤재, done

#65 [FIX] #63 - 버튼 Drawable 추가 및 적용
  presentation/src/main/res/drawable/bg_large_rounded_button.xml
  presentation/src/main/res/drawable/bg_medium_rounded_button.xml
  presentation/src/main/res/drawable/bg_small_rounded_button.xml
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/layout/item_cart.xml
  presentation/src/main/res/layout/item_detail_info.xml
  presentation/src/main/res/layout/item_food_grid.xml
  presentation/src/main/res/layout/item_food_horizontal.xml
  presentation/src/main/res/layout/item_food_vertical.xml
  presentation/src/main/res/layout/item_recently_viewed.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/style_rounded_button.xml
Labels: refactor, fix, 윤재, done

#68 [FEAT] #67 - 주문내역 리스트 화면
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/SimpleOrderListAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/res/layout/fragment_order_list.xml
  presentation/src/main/res/layout/item_order_simple.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, 윤재, 지혜, done

#70 [FEAT] 최근 본 상품 화면 구현
  data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/GetRecentlyUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/RecentlyUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/RecentlyViewedViewModel.kt
  presentation/src/main/res/layout/fragment_recently_viewed.xml
  presentation/src/main/res/layout/item_recently_viewed.xml
Labels: feature, 지혜, in progress

#72 [FIX] #71 - 음식 자세히 보기 화면
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/item_detail_images.xml
Labels: fix, 윤재, done

#74 [FIX] #73 - 주문 예상 시간 contracts에 추가
  presentation/src/main/java/com/woowahan/ordering/ui/contracts/Contracts.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
Labels: fix, 윤재, done

#78 [FEAT] 주문 상세 화면 구현
  contracts/src/main/java/com/woowahan/ordering/contracts/DateUtil.kt
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/OrderListMapper.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/OrderedCartList.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailFooterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailHeaderAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailListAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/SimpleOrderListAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt
  presentation/src/main/res/layout/fragment_order_detail.xml
  presentation/src/main/res/layout/item_order_detail_footer.xml
  presentation/src/main/res/layout/item_order_detail_header.xml
  presentation/src/main/res/layout/item_order_detail_list.xml
  presentation/src/main/res/values/dimen_size.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, 윤재, 지혜, done

#80 [REFACTOR] 장바구니 로직 코드 개선
  data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/CartResult.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartResultUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartListItem.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
Labels: refactor

#82 [FEAT] #81 - Splash Screen
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/res/drawable/ic_splash.xml
  presentation/src/main/res/values/splash.xml
Labels: feature, 윤재, 지혜, done

#86 [FIX] #84 - 할인율 내림차순 정렬
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
Labels: fix, 지혜, done

#90 [FEAT] #83 - 배달 알림 추가
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/CartResult.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartListItem.kt
  presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/util/AlarmUtil.kt
  presentation/src/main/java/com/woowahan/ordering/util/NotificationUtil.kt
  presentation/src/main/java/com/woowahan/ordering/util/RandUtil.kt
  presentation/src/main/res/drawable/ic_app.xml
  presentation/src/main/res/drawable/ic_notification.xml
Labels: feature, 윤재, 지혜, done

#93 [FEAT] #91 - 주문 상세 화면 새로고침 구현 및 버그 수정
  contracts/src/main/java/com/woowahan/ordering/contracts/Contracts.kt
  contracts/src/main/java/com/woowahan/ordering/contracts/DateUtil.kt
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailHeaderAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_order_detail.xml
  presentation/src/main/res/layout/item_order_detail_header.xml
  presentation/src/main/res/menu/menu_toolbar_order.xml
Labels: feature, 지혜, done

#95 [REFECTOR] #92 - RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemRecentlyViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
  presentation/src/main/res/layout/fragment_recently_viewed.xml
  presentation/src/main/res/layout/item_cart_recently.xml
  presentation/src/main/res/layout/item_recently_grid.xml
  presentation/src/main/res/layout/item_recently_horizontal.xml
Labels: refactor, 윤재, done

#98 [FIX] #97 - binding nullable
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
Labels: fix, 윤재, done

#100 [FIX] #99 - 자세히 보기 화면 썸네일 가져올 때 clear하기
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailThumbImagesAdapter.kt
Labels: fix, 윤재, done

#101 [REFECTOR] #92 - 아이템 클릭 이벤트 연결
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
Labels: fix, 윤재, done

#103 [REFECTOR] #102 - 프래그먼트 TAG 추가
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
Labels: refactor, 윤재, done

#105 [FIX] #99 - 화면이 제거되어 팅기는 버그
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
Labels: fix, 윤재, done

#107 [FIX] #106 - ItemDecorator 관련된 Grid Spacing 오류
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
Labels: fix, 윤재, done

#108 [FIX] #97 - 리스트 아이템 헤더부분 Space 수정
  presentation/src/main/res/layout/item_count_and_filter.xml
  presentation/src/main/res/layout/item_food_best.xml
  presentation/src/main/res/layout/item_type_and_filter.xml
Labels: fix, 윤재, done

#112 [FIX] #111 - Background 색상이 잘려서 표시되는 버그 수정
  presentation/src/main/res/layout/fragment_order_detail.xml
Labels: fix, 윤재, done

#113 [FIX] #97 - 기획전 아이템 Space 없어지는 버그 수정
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
Labels: fix, 윤재, done

#114 [FIX] #109 - 장바구니 화면 하단 최근 본 상품 Spece 사라지는 버그 수정
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
Labels: fix, 윤재, done

#116 [FIX] #115 - RecentlyViewedFragment
  presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
  presentation/src/main/res/layout/fragment_recently_viewed.xml
Labels: fix, 윤재, done

#119 [FIX] #118 - Constant
  constants/.gitignore
  constants/build.gradle
  constants/src/main/java/com/woowahan/ordering/constants/Constants.kt
  data/build.gradle
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodDetailMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/OrderListMapper.kt
  data/src/main/java/com/woowahan/ordering/data/util/MoneyUtil.kt
  domain/build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailFooterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/DateUtil.kt
  settings.gradle
Labels: fix, 윤재, done

#121 [REFECTOR] #120 - Notification 리팩토링
  presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt
  presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt
  presentation/src/main/java/com/woowahan/ordering/util/NotificationUtil.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor, 윤재, done

#128 [CHORE] #126 - 하드코딩된 스트링 제거
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/res/values/strings.xml
Labels: 지혜, done, chore

#127 [FIX] #125 - 장바구니 데이터 타입 수정 및 중복되는 코드 제거
  data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/FoodMapper.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt
  data/src/main/java/com/woowahan/ordering/data/util/MoneyUtil.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemRecentlyViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartDialogFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/IsExistsCartDialogFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/layout/item_cart.xml
  presentation/src/main/res/layout/item_order_detail_list.xml
  presentation/src/main/res/values/strings.xml
Labels: refactor, fix, 지혜

#124 [FIX] #117 - MainActivity Toolbar의 Order Badge 표시
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/entity/OrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/OrderMapper.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/Order.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/IsExistNotDeliveredOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/UpdateOrderUseCase.kt
  presentation/build.gradle
  presentation/src/androidTest/java/com/woowahan/ordering/OrderDaoTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
  presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/worker/DeliveryTimeWorker.kt
  presentation/src/main/res/layout/action_order.xml
Labels: fix, 윤재, done

#132 [FEAT] 네트워크 연결이 없는 경우 대응
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/ToastUtil.kt
  presentation/src/main/res/drawable/ic_bad.xml
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/fragment_detail.xml
  presentation/src/main/res/layout/fragment_main_dish.xml
  presentation/src/main/res/layout/fragment_other_dish.xml
  presentation/src/main/res/layout/layout_no_internet.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, 지혜, done

#130 [FIX] #129 - 장바구니 어댑터 개선
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/ToastUtil.kt
  presentation/src/main/res/drawable/ic_bad.xml
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/fragment_detail.xml
  presentation/src/main/res/layout/fragment_main_dish.xml
  presentation/src/main/res/layout/fragment_other_dish.xml
  presentation/src/main/res/layout/item_total_price.xml
  presentation/src/main/res/layout/layout_no_internet.xml
  presentation/src/main/res/values/strings.xml
Labels: fix, 지혜, done

#135 [REFACTOR] #134 - 여러 플로우 관찰 코드 수정
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
Labels: refactor, 지혜, done

#137 [FIX] #136 - Networking 오류 처리
  data/src/main/java/com/woowahan/ordering/data/remote/base/BaseRemote.kt
Labels: fix, 윤재, done

#139 [FIX] #138 - 장바구니 아이템 추가 시 반찬 리스트 정렬방식 초기화되는 버그
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
Labels: fix, 윤재, done

#142 [FIX] #141 - 상품 리스트 payload 적용
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
Labels: fix, 지혜

#140 [REFACTOR] #133 - 어댑터 클릭 리스너 생성자 주입 방식으로 변경
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
Labels: refactor, 지혜

#148 [FIX] #97 - onDestroy 필요없는 코드 제거
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
Labels: fix, 윤재, done

#146 [FEAT] #131 - 네트워크 연결이 없는 경우 대응
  data/src/main/java/com/woowahan/ordering/data/remote/base/BaseRemote.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/ordering/di/RemoteModule.kt
  presentation/src/main/java/com/woowahan/ordering/network/ConnectionInterceptor.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/uistate/ListUiState.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/util/NetworkUtil.kt
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/fragment_main_dish.xml
  presentation/src/main/res/layout/fragment_other_dish.xml
Labels: feature, 윤재, done

#150 [FIX] #149 - 화면 회전 시 이벤트 받기
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
Labels: refactor, fix, 윤재, done

#151 [FIX] #145 - 장바구니 목록 스크롤 문제 해결
  data/src/main/java/com/woowahan/ordering/data/datasource/RecentlyDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/RecentlyDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/RecentlyDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/RecentlyRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/CartResult.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/RecentlyRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartResultUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/GetSimpleRecentlyUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/RecentlyUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartListItem.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
Labels: fix, 지혜, done

#154 [FIX] #153 - 버튼 클릭이 중복되지 않도록 수정
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemRecentlyViewHolder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/ViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/listener/OnThrottleClickListener.kt
  presentation/src/main/res/layout/item_detail_info.xml
Labels: fix, 윤재, done

#157 [FIX] #156 - 메인요리 정렬 방식 변경 누락
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/TypeAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/res/values/strings.xml
Labels: fix, 지혜

#160 [FIX] #159 - 장바구니 바텀시트 화면회전 대응
  presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
  presentation/src/main/res/drawable/bg_rounded_bottom_sheet.xml
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/values/style_bottom_sheet.xml
Labels: fix, 지혜

#163 [FIX] #162 - 장바구니 성공/실패 처리
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/uistate/CartUiState.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: fix, 지혜

#168 [FIX] 필요없는 Dispatcher 제거
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
Labels: fix, 윤재, done

#172 [REFACTOR] #169 - Order UseCase의 Flow 관련 코드 수정
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/InsertOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/IsExistNotDeliveredOrderUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/UpdateOrderUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/worker/DeliveryTimeWorker.kt
Labels: refactor, 윤재, done

#173 [REFACTOR] #170 - History UseCase의 Flow 관련 코드 수정
  domain/src/main/java/com/woowahan/ordering/domain/usecase/history/GetHistoryUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/history/InsertHistoryUseCase.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/history/UpdateHistoryUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/HistoryUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/HistoryViewModel.kt
Labels: refactor, 지혜, done

#175 [FIX] #174 - 배달 리스트 페이징 구현
  constants/src/main/java/com/woowahan/ordering/constants/Constants.kt
  data/build.gradle
  data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt
  domain/build.gradle
  domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/SimpleOrderListAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt
Labels: fix, 윤재, done

#177 [REFACTOR] #176 - Notification 생성하는 클래스 나누기
  presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt
  presentation/src/main/java/com/woowahan/ordering/util/NotificationUtil.kt
Labels: refactor, 윤재, done

#179 [FIX] #178 - 최근 본 상품 페이징 적용
  data/src/main/java/com/woowahan/ordering/data/datasource/HistoryDataSource.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/HistoryDao.kt
  data/src/main/java/com/woowahan/ordering/data/local/datasource/HistoryDataSourceImpl.kt
  data/src/main/java/com/woowahan/ordering/data/repository/HistoryRepositoryImpl.kt
  domain/src/main/java/com/woowahan/ordering/domain/repository/HistoryRepository.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/history/GetHistoryUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/HistoryPagingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/HistoryFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/HistoryViewModel.kt
Labels: fix, 윤재, 지혜, done

#185 [FIX] #184 - 주문 내역 화면 수정 사항
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/res/drawable/ic_baseline_priority_high_24.xml
  presentation/src/main/res/layout/fragment_order_list.xml
  presentation/src/main/res/layout/layout_no_item.xml
  presentation/src/main/res/values/strings.xml
Labels: fix, 윤재, done

#187 [FIX] #186 - 최근 본 상품 없는 경우 대응
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
  presentation/src/main/res/layout/item_empty.xml
Labels: fix, 지혜, done

#189 [TEST] #188 - 테스트 코드 작성
  presentation/build.gradle
  presentation/src/androidTest/java/com/woowahan/ordering/CartDaoTest.kt
  presentation/src/androidTest/java/com/woowahan/ordering/ExampleInstrumentedTest.kt
  presentation/src/androidTest/java/com/woowahan/ordering/OrderDaoTest.kt
  presentation/src/test/java/com/woowahan/ordering/ExampleUnitTest.kt
  presentation/src/test/java/com/woowahan/ordering/data/local/CartDataSourceTest.kt
  presentation/src/test/java/com/woowahan/ordering/data/local/HistoryDataSourceTest.kt
  presentation/src/test/java/com/woowahan/ordering/data/local/OrderDataSourceTest.kt
  presentation/src/test/java/com/woowahan/ordering/data/remote/FoodDataSourceTest.kt
  presentation/src/test/java/com/woowahan/ordering/impl/dao/FakeCartDao.kt
  presentation/src/test/java/com/woowahan/ordering/impl/dao/FakeHistoryDao.kt
  presentation/src/test/java/com/woowahan/ordering/impl/dao/FakeOrderDao.kt
  presentation/src/test/java/com/woowahan/ordering/impl/service/FakeFoodService.kt
  presentation/src/test/java/com/woowahan/ordering/network/FakeCall.kt
  presentation/src/test/java/com/woowahan/ordering/paging/PagingCallback.kt
Labels: 윤재, 지혜, done, test

#193 [RELEASE] 1.0.1
  .github/workflows/cd.yml
  presentation/build.gradle
Labels: 윤재, 지혜

#197 [FIX] 다크모드로 변경 시 상세화면 리스너 초기화 문제 해결
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
Labels: fix, 지혜

#199 [FIX] #198 - Coil Placeholder 이미지 변경
  presentation/src/main/res/drawable/ic_placeholder.xml
Labels: fix, 윤재, done

#203 [FIX] #202 - 다른 화면에 갔다 왔을 때 필터 상태 저장
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/TypeAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
Labels: fix, 윤재, 지혜, done

#205 [FIX] #204 - 자세히 보기 화면 수정 사항
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailInfoAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/res/layout/item_detail_images.xml
Labels: fix, 윤재, 지혜, done

#214 [FIX] #213 - 상세화면 관련 버그
  domain/src/main/java/com/woowahan/ordering/domain/model/FoodDetail.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetFoodDetailUseCase.kt
  presentation/src/main/java/com/woowahan/ordering/di/usecase/FoodUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/item_detail_info.xml
  presentation/src/main/res/values/strings.xml
Labels: fix, 윤재, done

#216 [FIX] #215 - 기획전 화면 수정 사항
  presentation/src/main/java/com/woowahan/ordering/ui/widget/HorizontalRecyclerView.kt
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/item_food_best.xml
Labels: fix, 윤재, done

#218 [FIX] #217 - 다크모드 수정
  presentation/src/main/res/drawable/bg_spinner.xml
  presentation/src/main/res/drawable/bg_toolbar_cart_menu_count.xml
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_splash.xml
  presentation/src/main/res/layout/action_cart.xml
  presentation/src/main/res/layout/action_order.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/layout/fragment_order_detail.xml
  presentation/src/main/res/layout/item_header.xml
  presentation/src/main/res/layout/spinner_filter_dropdown.xml
  presentation/src/main/res/menu/menu_toolbar_order.xml
  presentation/src/main/res/values-night/colors.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/splash.xml
  presentation/src/main/res/values/style_bottom_sheet.xml
Labels: fix, 지혜, done

#220 [FIX] #219 - 네트워크 연결 메시지가 화면에 장시간 남아있는 버그 수정
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/SnackBarUtil.kt
Labels: fix, 지혜, done

#222 [FIX] #221 - 주문내역 배송 상태 업데이트 방법 추가
  data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/util/DateUtil.kt
  presentation/src/main/res/layout/item_order_simple.xml
  presentation/src/main/res/values/strings.xml
Labels: fix, 지혜, done

#224 [FIX] #223 - 상세화면에서 뒤로 가면 리스트 반짝이는 버그 해결
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
Labels: fix, 지혜, done

#226 [FIX] #225 - 상세화면 재진입 시 이전 상품이 유지되는 버그 해결
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/HistoryFragment.kt
  presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
Labels: fix, 지혜, done

#228 [RELEASE] v1.1
  README.md
  data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt
  data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
  data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/FoodDetail.kt
  domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
  domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetFoodDetailUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/ordering/di/usecase/FoodUseCaseModule.kt
  presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/HistoryFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
  presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/ordering/ui/widget/HorizontalRecyclerView.kt
  presentation/src/main/java/com/woowahan/ordering/util/DateUtil.kt
  presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
  presentation/src/main/java/com/woowahan/ordering/util/RecyclerViewUtil.kt
  presentation/src/main/java/com/woowahan/ordering/util/SnackBarUtil.kt
  presentation/src/main/res/drawable/bg_spinner.xml
  presentation/src/main/res/drawable/bg_toolbar_cart_menu_count.xml
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_splash.xml
  presentation/src/main/res/layout/action_cart.xml
  presentation/src/main/res/layout/action_order.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/bottom_sheet_cart.xml
  presentation/src/main/res/layout/fragment_best.xml
  presentation/src/main/res/layout/fragment_order_detail.xml
  presentation/src/main/res/layout/item_detail_info.xml
  presentation/src/main/res/layout/item_food_best.xml
  presentation/src/main/res/layout/item_header.xml
  presentation/src/main/res/layout/item_order_simple.xml
  presentation/src/main/res/layout/spinner_filter_dropdown.xml
  presentation/src/main/res/menu/menu_toolbar_order.xml
  presentation/src/main/res/values-night/colors.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/splash.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/style_bottom_sheet.xml
Labels: 윤재, 지혜

#230 [REFACTOR] #229 - Kotlin DSL 적용
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Config.kt
  buildSrc/src/main/java/Dependencies.kt
  constants/build.gradle.kts
  data/build.gradle
  data/build.gradle.kts
  data/proguard-rules.pro
  domain/build.gradle
  domain/build.gradle.kts
  presentation/build.gradle
  presentation/build.gradle.kts
  presentation/proguard-rules.pro
  settings.gradle.kts
Labels: refactor, 윤재, done

#232 [RELEASE] 1.1.1
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Config.kt
  buildSrc/src/main/java/Dependencies.kt
  constants/build.gradle.kts
  data/build.gradle
  data/build.gradle.kts
  data/proguard-rules.pro
  domain/build.gradle
  domain/build.gradle.kts
  presentation/build.gradle
  presentation/build.gradle.kts
  presentation/proguard-rules.pro
  settings.gradle.kts
Labels: 윤재, done
